steps:
  # 1. Construir la imagen del contenedor (Usando el nombre correcto en la ruta)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/frontend-dashboard/inclusion-social-img:$COMMIT_SHA', '.']

  # 2. Subir la imagen a Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/frontend-dashboard/inclusion-social-img:$COMMIT_SHA']

  # 3. Desplegar en Cloud Run (Nombre del servicio independiente)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'dashboard-inclusion-social' 
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/frontend-dashboard/inclusion-social-img:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--service-account'
      - '753170017712-compute@developer.gserviceaccount.com'

# Configuración de logging
options:
  logging: CLOUD_LOGGING_ONLY

# Imágenes que se guardarán
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/frontend-dashboard/inclusion-social-img:$COMMIT_SHA'
